/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import contrloador.GestionClientes;
import contrloador.GestionMascotas;
import contrloador.GestionTelefonos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Mascota;
import modelo.Telefono;
import vista.Login;
import rojerusan.RSPanelsSlider;
/**
 *
 * @author Bernardo
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Contenedor = new rojerusan.RSPanelsSlider();
        panelfondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelturno = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelregistro = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        pregistropersonal = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        Tipo = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        pregistroclientes = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        clinombre = new javax.swing.JTextField();
        clidireccion = new javax.swing.JTextField();
        clitelefono = new javax.swing.JTextField();
        clicorreo = new javax.swing.JTextField();
        clicedula = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        cclitelefono = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        cliid = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        panelfactura = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(763, 588, 588, 588));
        setMinimumSize(new java.awt.Dimension(763, 588));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("    TURNO");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("   FACTURA");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("  REGISTRAR");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("  INVENTARIO");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);

        jLabel41.setBackground(new java.awt.Color(204, 204, 204));
        jLabel41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 0, 0));
        jLabel41.setText("   SALIR");
        jLabel41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        jLabel41.setOpaque(true);
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel41);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 110, 550);

        panelfondo.setBackground(new java.awt.Color(153, 0, 102));
        panelfondo.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ZOOUDABLE");
        panelfondo.add(jLabel2);
        jLabel2.setBounds(80, 220, 510, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        panelfondo.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 550);

        Contenedor.add(panelfondo, "card2");

        panelturno.setName("panelturno"); // NOI18N
        panelturno.setLayout(null);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RAZA :");
        panelturno.add(jLabel10);
        jLabel10.setBounds(40, 230, 90, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOMBRE MASCOTA(ALIAS )");
        panelturno.add(jLabel12);
        jLabel12.setBounds(30, 130, 170, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TURNO # :");
        panelturno.add(jLabel14);
        jLabel14.setBounds(50, 40, 70, 16);
        panelturno.add(jTextField1);
        jTextField1.setBounds(150, 220, 70, 22);

        jButton1.setFont(new java.awt.Font("Garamond", 1, 13)); // NOI18N
        jButton1.setText("CREAR TURNO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelturno.add(jButton1);
        jButton1.setBounds(50, 440, 130, 25);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DESCRIPCION :");
        panelturno.add(jLabel16);
        jLabel16.setBounds(250, 350, 140, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelturno.add(jScrollPane1);
        jScrollPane1.setBounds(430, 350, 166, 150);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panelturno.add(jTextField6);
        jTextField6.setBounds(210, 130, 160, 22);
        panelturno.add(jTextField2);
        jTextField2.setBounds(140, 40, 70, 22);

        jButton9.setFont(new java.awt.Font("Garamond", 1, 13)); // NOI18N
        jButton9.setText("VERIFICAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelturno.add(jButton9);
        jButton9.setBounds(210, 440, 120, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/48414530_1903087569808413_8354147755102306304_n (1).jpg"))); // NOI18N
        panelturno.add(jLabel8);
        jLabel8.setBounds(0, 0, 640, 540);

        Contenedor.add(panelturno, "card3");

        panelregistro.setName("panelregistro"); // NOI18N
        panelregistro.setLayout(null);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jButton3.setText("PERSONAL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelregistro.add(jButton3);
        jButton3.setBounds(340, 210, 180, 80);

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jButton4.setText("CLIENTES ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelregistro.add(jButton4);
        jButton4.setBounds(110, 210, 190, 80);

        jLabel24.setBackground(new java.awt.Color(0, 102, 102));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/49899278_550625465454970_3718882791421640704_n.jpg"))); // NOI18N
        jLabel24.setOpaque(true);
        panelregistro.add(jLabel24);
        jLabel24.setBounds(0, -10, 640, 550);

        Contenedor.add(panelregistro, "card5");

        pregistropersonal.setName("pregistropersonal"); // NOI18N
        pregistropersonal.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 102));
        jLabel25.setText("CEDULA :");
        pregistropersonal.add(jLabel25);
        jLabel25.setBounds(40, 70, 60, 16);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("CARGO :");
        pregistropersonal.add(jLabel26);
        jLabel26.setBounds(40, 150, 50, 10);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("CONTRASEÑA :");
        pregistropersonal.add(jLabel27);
        jLabel27.setBounds(30, 210, 90, 15);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("EDAD :");
        pregistropersonal.add(jLabel28);
        jLabel28.setBounds(50, 290, 37, 16);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("TELEFONO :");
        pregistropersonal.add(jLabel29);
        jLabel29.setBounds(40, 360, 70, 16);

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("DIRECCION :");
        pregistropersonal.add(jLabel30);
        jLabel30.setBounds(300, 280, 80, 16);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("PROFECION :");
        pregistropersonal.add(jLabel31);
        jLabel31.setBounds(300, 70, 70, 16);

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 102));
        jLabel33.setText("NOMBRE :");
        pregistropersonal.add(jLabel33);
        jLabel33.setBounds(300, 210, 60, 16);

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText("USUARIO :");
        pregistropersonal.add(jLabel32);
        jLabel32.setBounds(300, 140, 70, 16);
        pregistropersonal.add(jTextField15);
        jTextField15.setBounds(150, 70, 120, 22);
        pregistropersonal.add(jTextField16);
        jTextField16.setBounds(150, 210, 110, 22);
        pregistropersonal.add(jTextField17);
        jTextField17.setBounds(150, 280, 120, 22);
        pregistropersonal.add(jTextField18);
        jTextField18.setBounds(150, 360, 120, 22);
        pregistropersonal.add(jTextField19);
        jTextField19.setBounds(410, 70, 130, 22);
        pregistropersonal.add(jTextField20);
        jTextField20.setBounds(410, 140, 150, 22);
        pregistropersonal.add(jTextField21);
        jTextField21.setBounds(410, 210, 150, 22);
        pregistropersonal.add(jTextField22);
        jTextField22.setBounds(410, 280, 140, 22);
        pregistropersonal.add(jTextField23);
        jTextField23.setBounds(150, 150, 120, 22);

        jButton5.setText("BUSCAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pregistropersonal.add(jButton5);
        jButton5.setBounds(290, 450, 100, 40);

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO", "MOVIL", "CONVENCIONAL" }));
        pregistropersonal.add(Tipo);
        Tipo.setBounds(150, 400, 120, 22);

        jButton8.setText("REGISTRAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pregistropersonal.add(jButton8);
        jButton8.setBounds(160, 450, 100, 40);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/50026326_523910904786569_5848442999729553408_n.jpg"))); // NOI18N
        pregistropersonal.add(jLabel40);
        jLabel40.setBounds(0, 0, 650, 550);

        Contenedor.add(pregistropersonal, "card6");

        pregistroclientes.setName("pregistroclientes"); // NOI18N
        pregistroclientes.setLayout(null);

        jLabel34.setText("NOMBRE :");
        pregistroclientes.add(jLabel34);
        jLabel34.setBounds(80, 130, 58, 16);

        jLabel35.setText("DIRECCION :");
        pregistroclientes.add(jLabel35);
        jLabel35.setBounds(80, 190, 73, 16);

        jLabel36.setText("TELEFONO :");
        pregistroclientes.add(jLabel36);
        jLabel36.setBounds(80, 250, 70, 16);

        jLabel37.setText("EMAIL :");
        pregistroclientes.add(jLabel37);
        jLabel37.setBounds(90, 340, 44, 16);

        jLabel38.setText("CEDULA :");
        pregistroclientes.add(jLabel38);
        jLabel38.setBounds(80, 60, 60, 16);
        pregistroclientes.add(clinombre);
        clinombre.setBounds(160, 130, 120, 30);
        pregistroclientes.add(clidireccion);
        clidireccion.setBounds(160, 190, 120, 30);
        pregistroclientes.add(clitelefono);
        clitelefono.setBounds(160, 250, 120, 30);
        pregistroclientes.add(clicorreo);
        clicorreo.setBounds(160, 330, 120, 30);

        clicedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicedulaActionPerformed(evt);
            }
        });
        pregistroclientes.add(clicedula);
        clicedula.setBounds(170, 60, 120, 30);

        jButton6.setFont(new java.awt.Font("Garamond", 1, 13)); // NOI18N
        jButton6.setText("ELIMINAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pregistroclientes.add(jButton6);
        jButton6.setBounds(440, 460, 120, 60);

        cclitelefono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO", "M","C" }));
        pregistroclientes.add(cclitelefono);
        cclitelefono.setBounds(340, 250, 150, 22);

        jButton10.setFont(new java.awt.Font("Garamond", 1, 13)); // NOI18N
        jButton10.setText("REGISTRAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pregistroclientes.add(jButton10);
        jButton10.setBounds(20, 460, 107, 60);

        jButton11.setFont(new java.awt.Font("Garamond", 1, 13)); // NOI18N
        jButton11.setText("BUSCAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        pregistroclientes.add(jButton11);
        jButton11.setBounds(150, 460, 110, 60);

        jButton12.setFont(new java.awt.Font("Garamond", 1, 13)); // NOI18N
        jButton12.setText("ACTUALIZAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        pregistroclientes.add(jButton12);
        jButton12.setBounds(290, 460, 120, 60);

        cliid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliidActionPerformed(evt);
            }
        });
        pregistroclientes.add(cliid);
        cliid.setBounds(400, 70, 120, 30);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/48413169_311199442828618_5704288482638168064_n.png"))); // NOI18N
        pregistroclientes.add(jLabel39);
        jLabel39.setBounds(0, 0, 650, 550);

        Contenedor.add(pregistroclientes, "card7");

        panelfactura.setName("panelfactura"); // NOI18N
        panelfactura.setLayout(null);

        jLabel4.setText("FECHA :");
        panelfactura.add(jLabel4);
        jLabel4.setBounds(40, 30, 50, 16);

        jLabel17.setText("DIRECCION :");
        panelfactura.add(jLabel17);
        jLabel17.setBounds(40, 100, 70, 16);

        jLabel18.setText("NOMBRE :");
        panelfactura.add(jLabel18);
        jLabel18.setBounds(40, 60, 50, 16);

        jLabel19.setText("EMAIL :");
        panelfactura.add(jLabel19);
        jLabel19.setBounds(40, 140, 44, 16);

        jLabel20.setText("DI :");
        panelfactura.add(jLabel20);
        jLabel20.setBounds(300, 130, 34, 16);

        jLabel21.setText("TELEFONO :");
        panelfactura.add(jLabel21);
        jLabel21.setBounds(300, 100, 60, 16);
        panelfactura.add(jTextField7);
        jTextField7.setBounds(120, 60, 90, 22);
        panelfactura.add(jTextField8);
        jTextField8.setBounds(120, 100, 90, 22);
        panelfactura.add(jTextField9);
        jTextField9.setBounds(110, 140, 100, 22);
        panelfactura.add(jTextField10);
        jTextField10.setBounds(370, 100, 110, 22);
        panelfactura.add(jTextField11);
        jTextField11.setBounds(350, 130, 130, 22);
        panelfactura.add(jTextField12);
        jTextField12.setBounds(120, 30, 90, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CANTIDAD", "DESCRIPCION", "V.UNITARIO", "V.TOTAL"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        panelfactura.add(jScrollPane2);
        jScrollPane2.setBounds(70, 210, 452, 120);

        jLabel22.setText("A PAGAR :");
        panelfactura.add(jLabel22);
        jLabel22.setBounds(390, 370, 60, 16);

        jLabel23.setText("VALOR CONSULTA :");
        panelfactura.add(jLabel23);
        jLabel23.setBounds(390, 400, 110, 16);
        panelfactura.add(jTextField13);
        jTextField13.setBounds(460, 370, 90, 22);
        panelfactura.add(jTextField14);
        jTextField14.setBounds(500, 400, 90, 22);

        jButton2.setText("CONFIRMAR");
        panelfactura.add(jButton2);
        jButton2.setBounds(420, 480, 100, 25);

        Contenedor.add(panelfactura, "card4");

        jLabel42.setText("jLabel42");
        Contenedor.add(jLabel42, "card8");

        jPanel1.add(Contenedor);
        Contenedor.setBounds(110, 0, 650, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(3, 0, 770, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
         Contenedor.setPanelSlider(20, panelturno, RSPanelsSlider.DIRECT.DOWN);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GestionMascotas gm= new GestionMascotas();
        ArrayList<Mascota>lista=gm.getListMascota(); //Lista de Mascota
        
        for (int i = 0; i <lista.size(); i++) {
            System.out.println(lista.get(i).getId());
        
       // new Login().setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Contenedor.setPanelSlider(20, panelfactura, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Contenedor.setPanelSlider(20,pregistroclientes, RSPanelsSlider.DIRECT.DOWN.UP);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Contenedor.setPanelSlider(20,pregistropersonal, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
         Contenedor.setPanelSlider(20,panelregistro, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    //ELIMINAR---------------------------
// TODO add your handling code here:
        
        
        
        new GestionClientes().EliminarCliente(clicedula.getText());
        limpiar();
        
        
        //GestionClientes gc=new GestionClientes();
        /*GestionTelefonos gt=new GestionTelefonos();
        Telefono tel=new Telefono();
        tel.setId(5);
        tel.setEmp_id(1);
        tel.setNumero(clitelefono.getText());
        tel.setTipo("m");
        gt.InsertTelefono(tel);*/
        
        /*Cliente cli=new Cliente();
        cli.setId(6);
        cli.setCedula(clicedula.getText());
        cli.setNombre(clinombre.getText());
        cli.setDireccion(clidireccion.getText());
        cli.setTelefonos(tel);
        cli.setCorreo(clicorreo.getText());
        gc.InsertCliente(cli);*/
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        // INSERTAR ---------------------------------
         Cliente cliente= new Cliente();
        
        
        cliente.setId(new GestionClientes().getListCliente().size()+1);
        cliente.setNombre(clinombre.getText());
        cliente.setCedula(clicedula.getText());
        cliente.setDireccion(clidireccion.getText());
        cliente.setTelefono(clitelefono.getText());
        cliente.setCorreo(clicorreo.getText());
        new GestionClientes().InsertCliente(cliente);
        
        cliid.setText(String.valueOf(cliente.getId()));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        
        if(Error(clicedula.getText())){
        Cliente cliente= new GestionClientes().getBuscarCliente(clicedula.getText());
        
        cliid.setText(String.valueOf(cliente.getId()));
        clinombre.setText(cliente.getNombre());
        clitelefono.setText(cliente.getTelefono());
        clidireccion.setText(cliente.getDireccion());
        clicorreo.setText(cliente.getCorreo());
        
        
       // cliente.setNombre(clinombre.getText());
      
        
//         TODO add your handling code here:
        }else{
            JOptionPane.showMessageDialog(null,"Valor no encontrado");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here
        //ACTUALIZAR ----------------------------
        Cliente cliente= new Cliente();
        
        
        cliente.setId(Integer.parseInt(cliid.getText())); //
        cliente.setNombre(clinombre.getText());
        cliente.setCedula(clicedula.getText());
        cliente.setDireccion(clidireccion.getText());
        cliente.setTelefono(clitelefono.getText());
        cliente.setCorreo(clicorreo.getText());
        
        /*ArrayList<Cliente>lista=new ArrayList<>();
        lista.add(cliente);
        for (int i = 0; i < lista.size(); i++) {
            System.out.println(lista.get(i).getCedula());
        }*/
        
        
        new GestionClientes().ActualizarCliente(cliente);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void clicedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clicedulaActionPerformed

    private void cliidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliidActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSPanelsSlider Contenedor;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JComboBox<String> cclitelefono;
    private javax.swing.JTextField clicedula;
    private javax.swing.JTextField clicorreo;
    private javax.swing.JTextField clidireccion;
    private javax.swing.JTextField cliid;
    private javax.swing.JTextField clinombre;
    private javax.swing.JTextField clitelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panelfactura;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JPanel panelregistro;
    private javax.swing.JPanel panelturno;
    private javax.swing.JPanel pregistroclientes;
    private javax.swing.JPanel pregistropersonal;
    // End of variables declaration//GEN-END:variables


public void limpiar(){ // Metodo para limpiar los jtextfield

  cliid.setText("");
        clinombre.setText("");
        clitelefono.setText("");
        clidireccion.setText("");
        clicorreo.setText("");
}
public boolean Error(String cedula){ //Metodo para el error
    boolean mensaje= false;
    for (int i = 0; i < new GestionClientes().getListCliente().size(); i++) {
        if(new GestionClientes().getListCliente().get(i).getCedula().equals (cedula))// Compara con todos los clientes de la lista 
            mensaje=true;
        break;// Sale del bucle
    }
    return mensaje;
}

}
